### ISSUE TITLE
Invalid password generation

### ISSUE THREAD

**Issue by Minecraftian14** [Minecraftian14/KIIT_Utility_Bot#1]
Sometimes the password generated are less than 100000, so they have fewer than 6 digits.
Meanwhile the bot seems to only recognize 6 digit passwords...

**Comment by HaxnovR** [comment]
Fixed and made a new PR
Replaced old random generation with the one below.
```java
Random random = new Random();
            int otp = random.ints(100000, 999999).findFirst().getAsInt();```
